//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    
    
    public partial class EIndividualCS {
        
        /// <summary>
        /// RadPanelBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPanelBar RadPanelBar1;
        
        /// <summary>
        /// RadClientExportManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadClientExportManager RadClientExportManager1;
        
        /// <summary>
        /// CustomersSeenByEmployeeIndividualRHC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadHtmlChart CustomersSeenByEmployeeIndividualRHC1;
        
        /// <summary>
        /// CustomersSeenByEmployeeIndividualODS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource CustomersSeenByEmployeeIndividualODS1;
        
        /// <summary>
        /// CustomersSeenByEmployeeIndividualG1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid CustomersSeenByEmployeeIndividualG1;
        
        /// <summary>
        /// AnimalsSeenByEmployeeIndividualRHC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadHtmlChart AnimalsSeenByEmployeeIndividualRHC1;
        
        /// <summary>
        /// AnimalsSeenByEmployeeIndividualODS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource AnimalsSeenByEmployeeIndividualODS1;
        
        /// <summary>
        /// AnimalsSeenByEmployeeIndividualG1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid AnimalsSeenByEmployeeIndividualG1;
        
        /// <summary>
        /// IncomeByEmployeeIndividualRHC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadHtmlChart IncomeByEmployeeIndividualRHC1;
        
        /// <summary>
        /// IncomeByEmployeeIndividualODS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource IncomeByEmployeeIndividualODS1;
        
        /// <summary>
        /// IncomeByEmployeeIndividualG1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid IncomeByEmployeeIndividualG1;
        
        /// <summary>
        /// IncomeFromAnimalTypeEmployeeIndividualRHC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadHtmlChart IncomeFromAnimalTypeEmployeeIndividualRHC1;
        
        /// <summary>
        /// IncomeFromAnimalTypeEmployeeIndividualODS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource IncomeFromAnimalTypeEmployeeIndividualODS1;
        
        /// <summary>
        /// IncomeFromAnimalTypeEmployeeIndividualG1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid IncomeFromAnimalTypeEmployeeIndividualG1;
    }
}
