//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public long Ref_Number { get; set; }
        public long Company_Ref { get; set; }
        public long User_Ref { get; set; }
        public string IP_Address { get; set; }
        public Nullable<int> Log_type { get; set; }
        public string Table_Name { get; set; }
        public string Message { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
