//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Profile
    {
        public long Company_Ref { get; set; }
        public long Cln_Number { get; set; }
        public Nullable<System.DateTime> First_Visit { get; set; }
        public System.DateTime Last_Updated { get; set; }
    
        public virtual Company_Profile Company_Profile { get; set; }
    }
}
