//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public long Ref_Number { get; set; }
        public long Company_Ref { get; set; }
        public long Branch_Ref { get; set; }
        public long User_Ref { get; set; }
        public long Param { get; set; }
        public string Value { get; set; }
    
        public virtual Branch_Profile Branch_Profile { get; set; }
        public virtual Company_Profile Company_Profile { get; set; }
        public virtual Param Param1 { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
