//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_For_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_For_Company()
        {
            this.KPI_For_User = new HashSet<KPI_For_User>();
        }
    
        public long Ref_Number { get; set; }
        public long Kpi_For_Business_Ref { get; set; }
        public long Company_Ref { get; set; }
    
        public virtual Company_Profile Company_Profile { get; set; }
        public virtual KPI_For_Business KPI_For_Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_For_User> KPI_For_User { get; set; }
    }
}
