//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_For_Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPI_For_Business()
        {
            this.KPI_For_Company = new HashSet<KPI_For_Company>();
        }
    
        public long Ref_Number { get; set; }
        public long Business_Type { get; set; }
        public long KPI { get; set; }
        public string Procedure_Name { get; set; }
    
        public virtual Business_Types Business_Types { get; set; }
        public virtual Key_Performance_Indexes Key_Performance_Indexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_For_Company> KPI_For_Company { get; set; }
    }
}
