//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI_For_User
    {
        public long Kpi_For_Company_Ref { get; set; }
        public string User_Ref { get; set; }
        public System.DateTime Last_Updated { get; set; }
        public Nullable<bool> Viewable { get; set; }
    
        public virtual KPI_For_Company KPI_For_Company { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
