//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Profile
    {
        public long Company_Ref { get; set; }
        public long Stf_Number { get; set; }
        public string Name { get; set; }
        public string Id { get; set; }
        public Nullable<long> Stf_Type { get; set; }
        public System.DateTime Last_Updated { get; set; }
    
        public virtual Company_Profile Company_Profile { get; set; }
        public virtual Staff_Types Staff_Types { get; set; }
    }
}
