//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Profile
    {
        public long Company_Ref { get; set; }
        public long Sub_Number { get; set; }
        public Nullable<long> First_Visit { get; set; }
        public Nullable<long> Subject_Type { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> Gender { get; set; }
        public System.DateTime Last_Updated { get; set; }
    
        public virtual Company_Profile Company_Profile { get; set; }
        public virtual Gender_Types Gender_Types { get; set; }
        public virtual Subject_Types Subject_Types { get; set; }
    }
}
