//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Items
    {
        public long Ref_Number { get; set; }
        public long Company_Ref { get; set; }
        public long Branch_Ref { get; set; }
        public long Trn_Number { get; set; }
        public long Trn_Item_Number { get; set; }
        public System.DateTime Trn_Date { get; set; }
        public long Cln_Number { get; set; }
        public long Sub_Number { get; set; }
        public long Stf_Number { get; set; }
        public long Prd_Number { get; set; }
        public short Mult { get; set; }
        public decimal Itm_Quantity { get; set; }
        public decimal Itm_Cost { get; set; }
        public decimal Itm_STotal { get; set; }
        public decimal Itm_Discount { get; set; }
        public decimal Itm_Total { get; set; }
        public System.DateTime Last_Updated { get; set; }
    }
}
