//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Logins
    {
        public string Login_Provider { get; set; }
        public string Provider_Key { get; set; }
        public string User_Id { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
