//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Profile()
        {
            this.Configurations = new HashSet<Configuration>();
            this.KPI_For_User = new HashSet<KPI_For_User>();
        }
    
        public long Ref_Number { get; set; }
        public long Company_Ref { get; set; }
        public string Name { get; set; }
        public bool Is_Admin { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public System.DateTime Last_Updated { get; set; }
    
        public virtual Company_Profile Company_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration> Configurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPI_For_User> KPI_For_User { get; set; }
    }
}
