//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Claims
    {
        public int Ref_Number { get; set; }
        public string User_Id { get; set; }
        public string Claim_Type { get; set; }
        public string Claim_Value { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
